name: geometric
author: Matan Lurey <matan@lurey.org>
version: 0.1.0
homepage: https://github.com/matanlurey/geometric
description: Geometric and 2D Math for Dart

environment:
  sdk: ">=1.21.0 <2.0.0"

dev_dependencies:
  test: "^0.12.18+1"
